# @source https://doc.rust-lang.org/book/ch02-00-guessing-game-tutorial.html

[package]
name = "guess-the-number"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
